chore: fix generate engine api report error

diff --git a/.github/workflows/cloud-e2e.yml b/.github/workflows/cloud-e2e.yml
--- a/.github/workflows/cloud-e2e.yml
+++ b/.github/workflows/cloud-e2e.yml
@@ -129,6 +129,7 @@ env:
   OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
   OSS_ENDPOINT: "oss-cn-zhangjiakou.aliyuncs.com"
   OSS_BUCKET: "kubeblocks-oss"
+  PYTHON_VERSION: "3.11"
 
 jobs:
   get-test-type:
@@ -386,26 +387,6 @@ jobs:
           CLOUD_E2E_HACK_DIR="${{ github.workspace }}/apecloud/e2e/hack"
           if [[ "${{ inputs.TEST_REPORT }}" == "true" && "${TEST_TYPE}" == "engine-test" ]]; then
               API_COVERAGE_SUMMARY=$(python3 test/report/parse_ginkgo.py summary ${test_file_log_path})
-          
-              engine_file_log="test_engine_api_result.txt"
-              engine_file_log_path="${{ github.workspace }}/${engine_file_log}"
-              touch ${engine_file_log_path} 
-              python3 test/report/parse_ginkgo.py summary ${test_file_log_path} > ${engine_file_log_path}
-          
-              cd test/report
-              bash update_test_period.sh ./md
-              mkdir -p reports/cn
-              for i in $(seq 1 3); do
-                  python3 ./report.py \
-                      --type=engine \
-                      --raw=${engine_file_log_path} \
-                      --main_report=TEST_REPORT_CLOUD_API_ENGINE.pdf
-                  gen_ret=$?
-                  if [[ $gen_ret -eq 0 ]]; then
-                      break
-                  fi
-                  sleep 1
-              done
           elif [[ -d "${CLOUD_E2E_HACK_DIR}" && "${{ inputs.TEST_REPORT }}" == "true" ]]; then
               cd ${CLOUD_E2E_HACK_DIR}
               if [[ -f "${CLOUD_E2E_HACK_DIR}/api-coverage.sh" ]]; then
@@ -467,24 +448,90 @@ jobs:
               cat ${coverage_file_log_path}
           fi
 
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        if: ${{ always() && matrix.test-type == 'engine-test' && inputs.TEST_REPORT == 'true' }}
+        with:
+          python-version: "${{ env.PYTHON_VERSION }}"
+
+      - name: checkout pystan2
+        uses: actions/checkout@v4
+        if: ${{ always() && matrix.test-type == 'engine-test' && inputs.TEST_REPORT == 'true' }}
+        with:
+          submodules: 'recursive'
+          repository: stan-dev/pystan2
+          ref: "v2.19.1.1"
+          path: pystan2
+
+      - name: install gen report env
+        if: ${{ always() && matrix.test-type == 'engine-test' && inputs.TEST_REPORT == 'true' }}
+        run: |
+          # locale gen zh_CN.UTF-8
+          sudo locale-gen zh_CN.UTF-8
+          sudo update-locale
+          locale -a
+          
+          # install wkhtmltopdf
+          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
+          sudo apt-get update
+          sudo apt-get install -y --no-install-recommends wkhtmltopdf fonts-wqy-zenhei fonts-wqy-microhei   
+          
+          # install Cython and NumPy
+          pip3 install Cython==3.0.9 NumPy==1.24.3
+          
+          # install pystan 2.19.1.1
+          cd pystan2
+          python3 setup.py install
+          
+          # install python requirements
+          cd ${{ github.workspace }}/test/report
+          sed -i 's/^appscript==.*/#appscript==/' requirements.txt
+          pip3 install -r requirements.txt
+
       - name: Setup ossutil
         uses: manyuanrong/setup-ossutil@v2.0
-        if: ${{ always() && matrix.test-type == 'engine-test' }}
+        if: ${{ always() && matrix.test-type == 'engine-test' && inputs.TEST_REPORT == 'true' }}
         with:
           access-key-id: "${{ env.OSS_KEY_ID }}"
           access-key-secret: "${{ env.OSS_KEY_SECRET }}"
           endpoint: "${{ env.OSS_ENDPOINT }}"
 
       - name: Upload engine report to oss
-        if: ${{ always() && matrix.test-type == 'engine-test' }}
+        if: ${{ always() && matrix.test-type == 'engine-test' && inputs.TEST_REPORT == 'true' }}
         id: upload_test_result
         run: |
+          file_log="test_result.log"
+          test_file_log_path="${{ github.workspace }}/${file_log}"
+          engine_file_log="test_engine_api_result.txt"
+          engine_file_log_path="${{ github.workspace }}/${engine_file_log}"
+          touch ${engine_file_log_path} 
+          python3 test/report/parse_ginkgo.py summary ${test_file_log_path} > ${engine_file_log_path}
+          
+          cd test/report
+          bash update_test_period.sh ./md
+          mkdir -p reports/cn
+          for i in $(seq 1 3); do
+              python3 ./report.py \
+                  --type=engine \
+                  --raw=${engine_file_log_path} \
+                  --main_report=TEST_REPORT_CLOUD_API_ENGINE.pdf
+              gen_ret=$?
+              if [[ $gen_ret -eq 0 ]]; then
+                  break
+              fi
+              sleep 1
+          done
+          
           export TZ='Asia/Shanghai'
           TEST_DATE="$(date +%Y%m%d)"
           echo test-date=${TEST_DATE} >> $GITHUB_OUTPUT
           APECLOUD_CURRENT_VERSION="${{ needs.get-test-type.outputs.current-version }}"
           OSS_DIR="oss://${{ env.OSS_BUCKET }}/reports/apecloud/${APECLOUD_CURRENT_VERSION}/${TEST_DATE}"
           upload_file_name="${{ github.workspace }}/test/report/reports/cn/TEST_REPORT_CLOUD_API_ENGINE.pdf"
+          if [[ ! -f "${upload_file_name}" ]]; then
+              echo "$(tput -T xterm setaf 3)::warning title=not found upload file$(tput -T xterm sgr0)"
+              exit 1
+          fi
           for i in $(seq 1 3); do
               ossutil cp -rf "${upload_file_name}" "${OSS_DIR}/${upload_file_name}"
               upload_ret=$?
