chore: increase upgrade and installer test timeout

diff --git a/.github/workflows/cloud-e2e-installer.yml b/.github/workflows/cloud-e2e-installer.yml
--- a/.github/workflows/cloud-e2e-installer.yml
+++ b/.github/workflows/cloud-e2e-installer.yml
@@ -80,6 +80,7 @@ jobs:
     name: installer-test-${{ matrix.k3s-version }}
     needs: [ get-cloud-branch ]
     runs-on: ubuntu-latest
+    timeout-minutes: 20
     outputs:
       installer-result-1-22: ${{ steps.install_kb_cloud.outputs.installer-result-1-22 }}
       bootstrapper-result-1-22: ${{ steps.deploy_kb_cloud_env.outputs.bootstrapper-result-1-22 }}
@@ -219,6 +220,15 @@ jobs:
                   echo "==================== pod ${installer_pod_name} logs ===================="
                   kubectl logs --tail 100 -n kb-cloud ${installer_pod_name}
               done 
+
+              echo "describe image pull error installer pod"
+              installer_error_pods=$(kubectl get pods -n kb-cloud | (grep "kb-cloud-installer" | grep -v "Completed" | grep -v "Running" | egrep "ImagePull|Pending|Evicted" || true) | awk '{print $1}')
+              echo "installer image pull error pod: ${installer_error_pods}"
+              for installer_error_pod in $(echo "${installer_error_pods}"); do
+                  echo "==================== pod ${installer_error_pod} describe ===================="
+                  kubectl describe pod -n kb-cloud ${installer_error_pod}
+                  echo ""
+              done
           
               # logs kb-cloud error pod 
               kb_cloud_error_pods=$(kubectl get pods -n kb-cloud | (grep -v "kb-cloud-installer" | grep -v "Completed" | grep -v "Running" | grep -v "NAME" | grep -v "ImagePull" || true) | awk '{print $1}')
@@ -403,7 +413,7 @@ jobs:
   upgrade-test:
     needs: [ get-cloud-branch ]
     runs-on: ubuntu-latest
-    timeout-minutes: 10
+    timeout-minutes: 20
     outputs:
       installer-result: ${{ steps.install_kb_cloud.outputs.installer-result }}
       upgrade-result: ${{ steps.upgrade_kb_cloud.outputs.upgrade-result }}
@@ -550,6 +560,15 @@ jobs:
                   kubectl logs --tail 100 -n kb-cloud ${installer_pod_name}
               done 
           
+              # describe image pull error installer pod
+              installer_error_pods=$(kubectl get pods -n kb-cloud | (grep "kb-cloud-installer" | grep -v "Completed" | grep -v "Running" | egrep "ImagePull|Pending|Evicted" || true) | awk '{print $1}')
+              echo "installer image pull error pod: ${installer_error_pods}"
+              for installer_error_pod in $(echo "${installer_error_pods}"); do
+                  echo "==================== pod ${installer_error_pod} describe ===================="
+                  kubectl describe pod -n kb-cloud ${installer_error_pod}
+                  echo ""
+              done
+          
               # logs kb-cloud error pod 
               kb_cloud_error_pods=$(kubectl get pods -n kb-cloud | (grep -v "kb-cloud-installer" | grep -v "Completed" | grep -v "Running" | grep -v "NAME" | grep -v "ImagePull" || true) | awk '{print $1}')
               echo "kb-cloud error pod: $kb_cloud_error_pods"
@@ -609,7 +628,7 @@ jobs:
           fi
 
       - name: check upgrade result
-        if: ${{ always() }}
+        if: ${{ always() && steps.install_kb_cloud.outputs.installer-result != '[FAILED]' }}
         id: upgrade_kb_cloud
         run: |
           upgrade_result="[PASSED]"
@@ -641,6 +660,15 @@ jobs:
               for kb_cloud_error_pod in $(echo "${kb_cloud_error_pods}"); do
                   echo "==================== pod ${kb_cloud_error_pod} logs ===================="
                   kubectl logs --tail 100 -n kb-cloud ${kb_cloud_error_pod}
+                  echo ""
+              done
+          
+              # describe image pull error kb-cloud pod
+              kb_cloud_image_pull_error_pods=$(kubectl get pods -n kb-cloud --no-headers | grep -v "Completed" | grep -v "Running" | egrep "ImagePull|Pending|Evicted" | awk '{print $1}')
+              echo "kb-cloud image pull error pod: $kb_cloud_image_pull_error_pods"
+              for kb_cloud_image_pull_error_pod in $(echo "${kb_cloud_image_pull_error_pods}"); do
+                  echo "==================== pod ${kb_cloud_image_pull_error_pod} describe ===================="
+                  kubectl describe pod -n kb-cloud ${kb_cloud_image_pull_error_pod}
                   echo ""
               done
               exit 1
