chore: change send e2e message

diff --git a/.github/workflows/cloud-e2e.yml b/.github/workflows/cloud-e2e.yml
--- a/.github/workflows/cloud-e2e.yml
+++ b/.github/workflows/cloud-e2e.yml
@@ -393,9 +393,9 @@ jobs:
           touch ${coverage_file_log_path} 
           API_COVERAGE_SUMMARY=""
           CLOUD_E2E_HACK_DIR="${{ github.workspace }}/apecloud/e2e/hack"
-          if [[ "${{ inputs.TEST_REPORT }}" == "true" && "${TEST_TYPE}" == "engine-test" ]]; then
+          if [[ ("${{ inputs.TEST_REPORT }}" == "true" || "${{ needs.get-test-type.outputs.cloud-branch }}" == "main") && "${TEST_TYPE}" == "engine-test" ]]; then
               API_COVERAGE_SUMMARY=$(python3 test/report/parse_ginkgo.py summary ${test_file_log_path})
-          elif [[ -d "${CLOUD_E2E_HACK_DIR}" && "${{ inputs.TEST_REPORT }}" == "true" ]]; then
+          elif [[ -d "${CLOUD_E2E_HACK_DIR}" && ("${{ inputs.TEST_REPORT }}" == "true" || "${{ needs.get-test-type.outputs.cloud-branch }}" == "main") ]]; then
               cd ${CLOUD_E2E_HACK_DIR}
               if [[ -f "${CLOUD_E2E_HACK_DIR}/api-coverage.sh" ]]; then
                   # api coverage summary
@@ -477,8 +477,7 @@ jobs:
                   --test-result "openapi-test-dev")
               export CI_JOB_URL="${CI_JOB_URL}"
               cd ${CLOUD_E2E_HACK_DIR}
-              cp -r ${test_file_log_path} ${CLOUD_E2E_HACK_DIR}/e2e.log
-              bash ./log-checker.sh
+              bash ./log-checker.sh --type openapi --log ${test_file_log_path}
           fi
 
       - name: Setup Python
@@ -530,7 +529,7 @@ jobs:
           endpoint: "${{ env.OSS_ENDPOINT }}"
 
       - name: Upload engine report to oss
-        if: ${{ always() && matrix.test-type == 'engine-test' && inputs.TEST_REPORT }}
+        if: ${{ always() && matrix.test-type == 'engine-test' && (inputs.TEST_REPORT || needs.get-test-type.outputs.cloud-branch == 'main') }}
         id: upload_test_result
         run: |
           file_log="test_result.log"
@@ -546,43 +545,45 @@ jobs:
           touch ${engine_file_log_path} 
           python3 test/report/parse_ginkgo.py "engine" ${test_file_log_path} > ${engine_file_log_path}
           cat "${engine_file_log_path}"
-          ENGINE_REPORT_FILE_NAME="${{ env.ENGINE_REPORT_FILE_NAME }}"
-          cd test/report
-          bash update_test_period.sh ./md
-          mkdir -p reports/cn
-          for i in $(seq 1 3); do
-              python3 ./report.py \
-                  --type=engine \
-                  --raw=${engine_file_log_path} \
-                  --main_report=${ENGINE_REPORT_FILE_NAME}
-              gen_ret=$?
-              if [[ $gen_ret -eq 0 ]]; then
-                  break
+          if [[ "${{ inputs.TEST_REPORT }}" == "true" ]]; then
+              ENGINE_REPORT_FILE_NAME="${{ env.ENGINE_REPORT_FILE_NAME }}"
+              cd test/report
+              bash update_test_period.sh ./md
+              mkdir -p reports/cn
+              for i in $(seq 1 3); do
+                  python3 ./report.py \
+                      --type=engine \
+                      --raw=${engine_file_log_path} \
+                      --main_report=${ENGINE_REPORT_FILE_NAME}
+                  gen_ret=$?
+                  if [[ $gen_ret -eq 0 ]]; then
+                      break
+                  fi
+                  sleep 1
+              done
+              
+              export TZ='Asia/Shanghai'
+              TEST_DATE="$(date +%Y%m%d)"
+              echo test-date=${TEST_DATE} >> $GITHUB_OUTPUT
+              APECLOUD_CURRENT_VERSION="${{ needs.get-test-type.outputs.current-version }}"
+              OSS_DIR="oss://${{ env.OSS_BUCKET }}/reports/apecloud/${APECLOUD_CURRENT_VERSION}/${TEST_DATE}"
+              upload_file_name="${{ github.workspace }}/test/report/reports/cn/${ENGINE_REPORT_FILE_NAME}"
+              if [[ ! -f "${upload_file_name}" ]]; then
+                  echo "$(tput -T xterm setaf 3)::warning title=not found upload file$(tput -T xterm sgr0)"
+                  exit 1
               fi
-              sleep 1
-          done
-          
-          export TZ='Asia/Shanghai'
-          TEST_DATE="$(date +%Y%m%d)"
-          echo test-date=${TEST_DATE} >> $GITHUB_OUTPUT
-          APECLOUD_CURRENT_VERSION="${{ needs.get-test-type.outputs.current-version }}"
-          OSS_DIR="oss://${{ env.OSS_BUCKET }}/reports/apecloud/${APECLOUD_CURRENT_VERSION}/${TEST_DATE}"
-          upload_file_name="${{ github.workspace }}/test/report/reports/cn/${ENGINE_REPORT_FILE_NAME}"
-          if [[ ! -f "${upload_file_name}" ]]; then
-              echo "$(tput -T xterm setaf 3)::warning title=not found upload file$(tput -T xterm sgr0)"
-              exit 1
+              for i in $(seq 1 3); do
+                  ossutil cp -rf "${upload_file_name}" "${OSS_DIR}/${ENGINE_REPORT_FILE_NAME}"
+                  upload_ret=$?
+                  if [[ $upload_ret -eq 0 ]]; then
+                      echo "$(tput -T xterm setaf 2)upload ${ENGINE_REPORT_FILE_NAME} to oss successfully$(tput -T xterm sgr0)"
+                      break
+                  else
+                      echo "$(tput -T xterm setaf 3)::warning title=upload ${ENGINE_REPORT_FILE_NAME} to oss failure$(tput -T xterm sgr0)"
+                  fi
+                  sleep 1
+              done
           fi
-          for i in $(seq 1 3); do
-              ossutil cp -rf "${upload_file_name}" "${OSS_DIR}/${ENGINE_REPORT_FILE_NAME}"
-              upload_ret=$?
-              if [[ $upload_ret -eq 0 ]]; then
-                  echo "$(tput -T xterm setaf 2)upload ${ENGINE_REPORT_FILE_NAME} to oss successfully$(tput -T xterm sgr0)"
-                  break
-              else
-                  echo "$(tput -T xterm setaf 3)::warning title=upload ${ENGINE_REPORT_FILE_NAME} to oss failure$(tput -T xterm sgr0)"
-              fi
-              sleep 1
-          done
 
   installer-test:
     needs: [ get-test-type ]
@@ -1060,7 +1061,7 @@ jobs:
               --result "$TEST_RESULT"
           
           TEST_TITLE_SUMMARY="[${CLOUD_BRANCH}] Cloud E2E API Coverage Summary [${date_ret}]"
-          if [[ -n "${API_COVERAGE_SUMMARY}" && "${{ inputs.TEST_REPORT }}" == "true" ]]; then
+          if [[ -n "${API_COVERAGE_SUMMARY}" && ("${{ inputs.TEST_REPORT }}" == "true" || "${{ needs.get-test-type.outputs.cloud-branch }}" == "main") ]]; then
               echo "API_COVERAGE_SUMMARY:${API_COVERAGE_SUMMARY}"
               API_COVERAGE_SUMMARY_TMP="$(bash .github/utils/utils.sh \
                   --type 42 \
@@ -1077,7 +1078,7 @@ jobs:
           
           TEST_TITLE_ENGINE_SUMMARY="[${CLOUD_BRANCH}] Cloud E2E Engine API Summary [${date_ret}]"
           ENGINE_REPORT_FILE_NAME="${{ env.ENGINE_REPORT_FILE_NAME }}"
-          if [[ -n "${ENGINE_API_SUMMARY}" && "${{ inputs.TEST_REPORT }}" == "true" ]]; then
+          if [[ -n "${ENGINE_API_SUMMARY}" && ("${{ inputs.TEST_REPORT }}" == "true" || "${{ needs.get-test-type.outputs.cloud-branch }}" == "main") ]]; then
               APECLOUD_CURRENT_VERSION="${{ needs.get-test-type.outputs.current-version }}"
               TEST_DATE=${{ needs.e2e-test.outputs.test-date }}
               OSS_URL="https://${{ env.OSS_BUCKET }}.${{ env.OSS_ENDPOINT }}/reports/apecloud/${APECLOUD_CURRENT_VERSION}/${TEST_DATE}"
